### PR TITLE
Refactor out foods tests

### PR DESCRIPTION
**Pull request by VictoriaVasys**
@case-eee @stovermc Here's a start to refactoring tests; I'm not sure what would be appropriate next steps (Do we want to test each request in a separate test? Test our models & controllers separately?)

Also, I tried creating a directory called "integrations" within the test directory, and then `npm test` failed, so not sure how to handle new directories.

### CODE REVIEW

**Comment by VictoriaVasys** [comment]
@case-eee @stovermc I'm also not sure if we can somehow send "ourReqeust" to the new test file so we don't have to create a new connection; I tried simply defining ourRequest in the before action under server & the tests below didn't recognize it... lmk if you have thoughts.

**Comment by case-eee** [comment]
@VictoriaVasys you could try using the --recursive flag when calling mocha. i believe you can specify that in your package.json file - then when you run `npm test` it will really run `mocha --recursive` this flag execute all tests in sub directories of the "test" folder. try this out 👍

**Comment by VictoriaVasys** [comment]
@case-eee Thanks for the thorough response! We will definitely try out that recursive mocha command. And will table additional/more segmented testing until after we're done with base requirements. Thanks!

**Comment by stovermc** [comment]
@VictoriaVasys I like that you have pulled meals-tests out into its own test file. I think this will help with our organization even though both tests are pretty long files.

@case-eee thanks for the response. Will definitely work towards an MVP before working on more module test.

**Pull request merged**
