### PR TITLE
[Finishes #148109549] DELETE Food

### PR DESCRIPTION
**Pull request by VictoriaVasys**
@case-eee @stovermc Even though in class, we returned a 404 if there were no rows in our table, should we instead be returning a 422 with explicit reasons why? (eg. for 'get api/v1/foods', we could say there are no entries & for 'delete api/v1/foods', we could say the last food was deleted or something like that)

Also, we'd like to refactor our "controllers" out; should we namespace them like 'app/models/api/v1/foodsController.js'?

### CODE REVIEW

**Comment by case-eee** [comment]
@VictoriaVasys i think returning a 404 for the examples you mentioned is sufficient, but it doesn't hurt to be more specific. if you'd like to return a 422 and give a more explicit description of the issue, i support that!

i'd have a `lib` directory in the root and then `controllers` and `models` directories under that. then, in those directories you can have your files. does that make sense?

**Comment by VictoriaVasys** [comment]
@case-eee Sounds good, thanks! As far as directory structure, totally with you on controllers & models, but in Rails, we namespaced api/v1/controller.rb for controllers; would you do the same thing or just have controllers directly in the controller directory?

**Comment by case-eee** [comment]
since we're only creating one version of this api right now AND we only have an api, i'd stick with just a controllers directory then naming your controller accordingly within that folder. eventually, you'd probably have an `api` directory with a nested `v1` directory. since node doesn't care about the organization of the file structure (like Rails does), it's pretty easy to make that change when you get there!

**Comment by stovermc** [comment]
@VictoriaVasys nice work digging into the merge conflicts! Things look great.

**Pull request merged**
