### PR TITLE
[Finishes #148191201] Refactor Responses, Sad Path Testing

### PR DESCRIPTION
**Pull request by VictoriaVasys**
@case-eee @stovermc I added some sad paths for our put request, but not sure it's exactly what we want. If one property is entered correctly, but the other is not (e.g. {name: 'steak', malories: 500}), do we want to update the property that was entered correctly or return an error for the whole request? OR do we want to only accept one property change at a time?

### CODE REVIEW

**Comment by case-eee** [comment]
@VictoriaVasys if any input is incorrect, let's send an error message back letting the user know what they need to correct 👍 

if you'd like to instead only accept one property to update at a time, i'm fine with that as well!

**Comment by VictoriaVasys** [comment]
@case-eee sounds good! We'll discuss & use our best judgement :)

**Comment by case-eee** [comment]
sounds good 👍

**Comment by stovermc** [comment]
@VictoriaVasys Refactor looks great!

**Pull request merged**
